import { ReceiptText, TrendingUp, WalletCards } from 'lucide-react'
import { EmptyState, ErrorState, LoadingState } from '../../components/ui/AsyncState'
import { ownerApi } from '../../core/api/services'
import { useAsyncResource } from '../../core/api/useAsyncResource'
import { formatLkr } from '../../services/sriLankanData'

export function OwnerAnalyticsPage(){
 const resource=useAsyncResource(ownerApi.analytics, 7000);if(resource.loading)return <LoadingState label="Loading restaurant analytics…"/>;if(resource.error)return <ErrorState message={resource.error} retry={resource.retry}/>;const data=resource.data!
 return <>{resource.refreshError && <p className="error-banner" role="status">Refresh failed: {resource.refreshError}. Showing the last loaded data; retrying automatically.</p>}<div className="portal-title"><div><span className="eyebrow">Restaurant performance</span><h1>Analytics</h1><p>Revenue includes delivered and paid orders only.</p></div></div><div className="analytics-metrics owner-analytics-metrics"><article><small>Today&apos;s revenue</small><strong>{formatLkr(data.summary.todayRevenue)}</strong><span className="positive"><TrendingUp/>Today</span></article><article><small>Total revenue</small><strong>{formatLkr(data.summary.totalRevenue)}</strong><span className="positive"><WalletCards/>Delivered</span></article><article><small>All orders</small><strong>{data.summary.orderCount}</strong><span><ReceiptText/>Recorded</span></article><article><small>Completed orders</small><strong>{data.summary.completedOrders}</strong><span>Delivered</span></article><article><small>Average completed order</small><strong>{formatLkr(data.summary.averageOrderValue)}</strong><span>Per order</span></article></div><div className="portal-two-col"><section className="portal-card"><div className="portal-card__heading"><div><h2>Popular menu items</h2><p>Ranked by delivered quantity</p></div></div>{data.popularItems.length?<div className="ranking">{data.popularItems.map((item,index)=><div key={item._id??item.name}><b>{index+1}</b><span><strong>{item.name}</strong><small>{item.quantity} sold</small></span><em>{formatLkr(item.revenue)}</em></div>)}</div>:<EmptyState title="No item sales yet" message="Popular items appear after delivered orders."/>}</section><section className="portal-card"><div className="portal-card__heading"><div><h2>Recent sales</h2><p>Latest delivered and paid orders</p></div></div>{data.recentSales.length?<div className="compact-orders">{data.recentSales.map(order=><div className="compact-sale" key={order._id}><span><strong>#{order._id.slice(-6).toUpperCase()}</strong><small>{new Date(order.createdAt).toLocaleString('en-LK')}</small></span><b>{formatLkr(order.totalAmount)}</b></div>)}</div>:<EmptyState title="No completed sales" message="Delivered sales will appear here."/>}</section></div></>
}
