import { BellRing, Check, Clock3, PackageCheck, X } from 'lucide-react'
import { useMemo } from 'react'
import { orderApi } from '../../core/api/services'
import { useAsyncResource } from '../../core/api/useAsyncResource'
import type { ApiOrder, OrderStatus } from '../../core/types/api'
import { EmptyState, ErrorState, LoadingState } from '../../components/ui/AsyncState'
import { formatLkr } from '../../services/sriLankanData'

const columns: Array<{ label: string; statuses: OrderStatus[]; icon: typeof BellRing }> = [{ label:'Incoming',statuses:['placed'],icon:BellRing },{ label:'Preparing',statuses:['accepted','confirmed','preparing'],icon:Clock3 },{ label:'Ready for pickup',statuses:['ready_for_pickup','rider_assigned'],icon:PackageCheck }]
export function OwnerOrderBadgeV2({ status }: { status: OrderStatus }) { return <span className={`owner-status owner-status--${status.replaceAll('_','-')}`}>{status.replaceAll('_',' ')}</span> }
export function OwnerOrdersV2Page() {
  const resource = useAsyncResource(orderApi.all); const orders = useMemo(() => resource.data ?? [], [resource.data])
  const update = async (order: ApiOrder, status: OrderStatus) => { const previous = resource.data; resource.setData(orders.map((item) => item._id === order._id ? { ...item, status } : item)); try { await orderApi.status(order._id, status) } catch { resource.setData(previous); void resource.retry() } }
  const grouped = useMemo(() => columns.map((column) => ({ ...column, orders: orders.filter((order) => column.statuses.includes(order.status)) })), [orders])
  if (resource.loading) return <LoadingState label="Loading restaurant orders…" />; if (resource.error) return <ErrorState message={resource.error} retry={resource.retry} />
  return <><div className="portal-title"><div><span className="eyebrow">Kitchen command centre</span><h1>Orders</h1><p>Review incoming orders and keep customers and riders updated.</p></div><div className="live-indicator"><span /> Connected to Foodie</div></div>{orders.length === 0 ? <EmptyState title="No orders yet" message="New customer orders will appear here as soon as they arrive." /> : <div className="order-board">{grouped.map((column) => { const Icon=column.icon; return <section key={column.label}><header><div><Icon /><h2>{column.label}</h2></div><span>{column.orders.length}</span></header><div>{column.orders.map((order) => { const customer = typeof order.customer === 'string' ? 'Customer' : order.customer.name; return <article className="kitchen-order" key={order._id}><div><strong>#{order._id.slice(-6).toUpperCase()}</strong><OwnerOrderBadgeV2 status={order.status} /></div><h3>{customer}</h3><ul>{order.items.map((item) => <li key={`${order._id}-${item.menuItem}`}>{item.quantity}× {item.name}</li>)}</ul><div className="kitchen-order__total"><span>Total</span><b>{formatLkr(order.totalAmount)}</b></div>{order.status === 'placed' && <div className="action-pair"><button onClick={() => void update(order,'declined')}><X /> Decline</button><button onClick={() => void update(order,'accepted')}><Check /> Accept</button></div>}{['accepted','confirmed'].includes(order.status) && <button className="button button--primary button--full" onClick={() => void update(order,'preparing')}>Start preparing</button>}{order.status === 'preparing' && <button className="button button--primary button--full" onClick={() => void update(order,'ready_for_pickup')}>Mark ready for pickup</button>}</article> })}{column.orders.length === 0 && <p className="column-empty">Nothing here right now.</p>}</div></section> })}</div>}</>
}
