import { BellRing, Check, Clock3, PackageCheck, X } from 'lucide-react'
import { useState } from 'react'
import { ownerOrders as initialOrders } from '../../services/portalService'
import type { OwnerOrderStatus } from '../../types'

export function OwnerOrderBadge({ status }: { status: OwnerOrderStatus }) { return <span className={`owner-status owner-status--${status.toLowerCase().replaceAll(' ','-')}`}>{status}</span> }
export function OwnerOrdersPage() {
  const [orders, setOrders] = useState(initialOrders); const update = (id: string, status: OwnerOrderStatus) => setOrders((all) => all.map((order) => order.id === id ? { ...order, status } : order))
  return <><div className="portal-title"><div><span className="eyebrow">Kitchen command center</span><h1>Orders</h1><p>Review incoming orders and keep every customer updated.</p></div><div className="live-indicator"><span /> Live updates on</div></div><div className="order-board">{(['New','Preparing','Ready for Pickup'] as OwnerOrderStatus[]).map((status) => <section key={status}><header><div>{status === 'New' ? <BellRing /> : status === 'Preparing' ? <Clock3 /> : <PackageCheck />}<h2>{status}</h2></div><span>{orders.filter((order) => order.status === status).length}</span></header><div>{orders.filter((order) => order.status === status).map((order) => <article className="kitchen-order" key={order.id}><div><strong>#{order.id}</strong><small>{order.placedAt}</small></div><h3>{order.customer}</h3><ul>{order.items.map((item) => <li key={item}>{item}</li>)}</ul><div className="kitchen-order__total"><span>Total</span><b>${order.total.toFixed(2)}</b></div>{status === 'New' && <div className="action-pair"><button onClick={() => update(order.id,'Declined')}><X /> Decline</button><button onClick={() => update(order.id,'Preparing')}><Check /> Accept</button></div>}{status === 'Preparing' && <button className="button button--primary button--full" onClick={() => update(order.id,'Ready for Pickup')}>Mark ready for pickup</button>}{status === 'Ready for Pickup' && <button className="button button--primary button--full" onClick={() => update(order.id,'Completed')}>Complete handoff</button>}</article>)}</div></section>)}</div></>
}
