import { BellRing, Check, Clock3, PackageCheck, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { EmptyState, ErrorState, LoadingState } from '../../components/ui/AsyncState'
import { orderApi, ownerApi } from '../../core/api/services'
import { useAsyncResource } from '../../core/api/useAsyncResource'
import type { ApiOrder, OrderStatus } from '../../core/types/api'
import { formatLkr } from '../../services/sriLankanData'

const columns: Array<{ label: string; statuses: OrderStatus[]; icon: typeof BellRing }> = [{label:'Incoming',statuses:['placed'],icon:BellRing},{label:'In progress',statuses:['accepted','confirmed','preparing'],icon:Clock3},{label:'Ready for pickup',statuses:['ready_for_pickup','rider_assigned'],icon:PackageCheck},{label:'History',statuses:['declined','picked_up','out_for_delivery','delivered','cancelled'],icon:Check}]
export function OwnerOrderBadgeV2({status}:{status:OrderStatus}){return <span className={`owner-status owner-status--${status.replaceAll('_','-')}`}>{status.replaceAll('_',' ')}</span>}
export function OwnerOrdersV2Page(){
 const resource=useAsyncResource(ownerApi.orders, 7000);const orders=useMemo(()=>resource.data??[],[resource.data]);const[busy,setBusy]=useState('');const[error,setError]=useState('')
 const update=async(order:ApiOrder,status:OrderStatus)=>{setBusy(order._id);setError('');try{await orderApi.status(order._id,status);await resource.retry()}catch(caught){setError(caught instanceof Error?caught.message:'Unable to update this order.')}finally{setBusy('')}}
 const grouped=useMemo(()=>columns.map(column=>({...column,orders:orders.filter(order=>column.statuses.includes(order.status))})),[orders])
 if(resource.loading)return <LoadingState label="Loading restaurant orders…"/>;if(resource.error)return <ErrorState message={resource.error} retry={resource.retry}/>
 return <>{resource.refreshError && <p className="error-banner" role="status">Refresh failed: {resource.refreshError}. Showing the last loaded data; retrying automatically.</p>}<div className="portal-title"><div><span className="eyebrow">Kitchen command centre</span><h1>Orders</h1><p>Only orders placed with your restaurant are shown.</p></div><div className="live-indicator"><span/>Connected to Foodie</div></div>{error&&<p className="error-banner" role="alert">{error}</p>}{orders.length===0?<EmptyState title="No orders yet" message="New customer orders will appear here."/>:<div className="order-board">{grouped.map(column=>{const Icon=column.icon;return <section key={column.label}><header><div><Icon/><h2>{column.label}</h2></div><span>{column.orders.length}</span></header><div>{column.orders.map(order=>{const customer=typeof order.customer==='string'?'Customer':order.customer.name;return <article className="kitchen-order" key={order._id}><div><Link to={`/owner/orders/${order._id}`}><strong>#{order._id.slice(-6).toUpperCase()}</strong></Link><OwnerOrderBadgeV2 status={order.status}/></div><h3>{customer}</h3><p>Payment: {order.paymentStatus} · {new Date(order.createdAt).toLocaleString()}</p><ul>{order.items.map(item=><li key={`${order._id}-${item.menuItem}`}>{item.quantity}× {item.name}</li>)}</ul><div className="kitchen-order__total"><span>Total</span><b>{formatLkr(order.totalAmount)}</b></div>{order.status==='placed'&&<div className="action-pair"><button disabled={busy===order._id} onClick={()=>void update(order,'declined')}><X/>Decline</button><button disabled={busy===order._id} onClick={()=>void update(order,'confirmed')}><Check/>Accept</button></div>}{order.status==='accepted'&&<button disabled={busy===order._id} className="button button--primary button--full" onClick={()=>void update(order,'confirmed')}>Confirm order</button>}{order.status==='confirmed'&&<button disabled={busy===order._id} className="button button--primary button--full" onClick={()=>void update(order,'preparing')}>Start preparing</button>}{order.status==='preparing'&&<button disabled={busy===order._id} className="button button--primary button--full" onClick={()=>void update(order,'ready_for_pickup')}>Mark ready for pickup</button>}</article>})}{column.orders.length===0&&<p className="column-empty">Nothing here right now.</p>}</div></section>})}</div>}</>
}
