import { resolveImageUrl } from '../../core/api/imageUrl'
import { ImagePlus } from 'lucide-react'
import { useCallback, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ErrorState, LoadingState } from '../../components/ui/AsyncState'
import { menuApi, ownerApi } from '../../core/api/services'
import { useAsyncResource } from '../../core/api/useAsyncResource'

export function OwnerMenuFormPage(){
 const{itemId}=useParams();const navigate=useNavigate();const loader=useCallback(async()=>{const restaurant=await ownerApi.restaurant();const item=itemId?await ownerApi.menuItem(itemId):null;return{restaurant,item}},[itemId]);const resource=useAsyncResource(loader);const[busy,setBusy]=useState(false);const[error,setError]=useState('')
 if(resource.loading)return <LoadingState label="Loading menu editor…"/>;if(resource.error)return <ErrorState message={resource.error} retry={resource.retry}/>
 const{restaurant,item}=resource.data!;const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!restaurant){setError('Create your restaurant before adding menu items.');return}const form=new FormData(event.currentTarget);const payload={restaurant:restaurant._id,name:String(form.get('name')).trim(),description:String(form.get('description')).trim(),category:String(form.get('category')).trim(),price:Number(form.get('price')),imageUrl:String(form.get('imageUrl')).trim()||undefined};setBusy(true);setError('');try{if(item)await menuApi.update(item._id,payload);else await menuApi.create(payload);navigate('/owner/menu',{replace:true})}catch(caught){setError(caught instanceof Error?caught.message:'Unable to save this menu item.')}finally{setBusy(false)}}
 return <><div className="portal-title"><div><Link to="/owner/menu">‹ Back to menu</Link><h1>{item?'Edit menu item':'Add menu item'}</h1><p>Saved changes are visible in your restaurant menu.</p></div></div>{error&&<p className="error-banner" role="alert">{error}</p>}<form className="portal-card menu-form-layout" onSubmit={event=>void save(event)}><div className="image-upload-placeholder">{item?.imageUrl?<img src={resolveImageUrl(item.imageUrl)} alt={item.name}/>:<><ImagePlus/><strong>Food image URL</strong><small>Add the URL in the form</small></>}</div><div className="form-grid"><label>Item name<input name="name" required defaultValue={item?.name}/></label><label>Category<input name="category" required defaultValue={item?.category}/></label><label className="full">Description<textarea name="description" defaultValue={item?.description}/></label><label>Price (Rs.)<input name="price" required min="0" step="0.01" type="number" defaultValue={item?.price}/></label><label>Image URL<input name="imageUrl" type="url" defaultValue={item?.imageUrl}/></label></div><footer className="form-actions"><Link className="button button--secondary" to="/owner/menu">Cancel</Link><button className="button button--primary" disabled={busy}>{busy?'Saving…':'Save item'}</button></footer></form></>
}
