import { resolveImageUrl } from '../../core/api/imageUrl'
import { Pencil, Plus, Search, Store, Trash2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { EmptyState, ErrorState, LoadingState } from '../../components/ui/AsyncState'
import { menuApi, ownerApi } from '../../core/api/services'
import { useAsyncResource } from '../../core/api/useAsyncResource'
import { formatLkr } from '../../services/sriLankanData'

export function OwnerMenuPage(){
 const resource=useAsyncResource(ownerApi.menu);const[query,setQuery]=useState('');const[category,setCategory]=useState('All');const[availability,setAvailability]=useState('All');const[busy,setBusy]=useState('');const[error,setError]=useState('')
 const items=useMemo(()=>resource.data??[],[resource.data]);const categories=useMemo(()=>['All',...new Set(items.map(item=>item.category))],[items]);const visible=useMemo(()=>items.filter(item=>(category==='All'||item.category===category)&&(availability==='All'||(availability==='Available')===item.available)&&`${item.name} ${item.description??''}`.toLowerCase().includes(query.toLowerCase())),[items,query,category,availability])
 const toggle=async(id:string)=>{setBusy(id);setError('');try{await menuApi.toggle(id);await resource.retry()}catch(caught){setError(caught instanceof Error?caught.message:'Unable to update item availability.')}finally{setBusy('')}}
 const remove=async(id:string)=>{if(!confirm('Delete this menu item? This cannot be undone.'))return;setBusy(id);setError('');try{await menuApi.remove(id);await resource.retry()}catch(caught){setError(caught instanceof Error?caught.message:'Unable to delete this menu item.')}finally{setBusy('')}}
 if(resource.loading)return <LoadingState label="Loading your menu…"/>;if(resource.error)return <ErrorState message={resource.error} retry={resource.retry}/>
 return <><div className="portal-title"><div><span className="eyebrow">Restaurant catalogue</span><h1>Menu Items</h1><p>Changes are saved to your restaurant menu.</p></div><Link className="button button--primary" to="/owner/menu/new"><Plus/>Add item</Link></div>{error&&<p className="error-banner" role="alert">{error}</p>}<div className="menu-toolbar menu-toolbar--wide"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search menu items"/></label><select value={category} onChange={event=>setCategory(event.target.value)}>{categories.map(value=><option key={value}>{value}</option>)}</select><select value={availability} onChange={event=>setAvailability(event.target.value)}><option>All</option><option>Available</option><option>Unavailable</option></select></div>{visible.length?<div className="owner-menu-grid">{visible.map(item=><article className={`owner-menu-card ${!item.available?'unavailable':''}`} key={item._id}>{item.imageUrl?<img src={resolveImageUrl(item.imageUrl)} alt={item.name}/>:<div className="owner-menu-photo"><Store/></div>}<div className="owner-menu-card__body"><span>{item.category}</span><h3>{item.name}</h3><p>{item.description}</p><footer><strong>{formatLkr(item.price)}</strong><div className="menu-card-actions"><Link aria-label={`Edit ${item.name}`} to={`/owner/menu/${item._id}/edit`}><Pencil/></Link><button disabled={busy===item._id} aria-label={`Delete ${item.name}`} onClick={()=>void remove(item._id)}><Trash2/></button></div></footer><button disabled={busy===item._id} className={`stock-toggle ${item.available?'on':''}`} onClick={()=>void toggle(item._id)}>{item.available?'Available':'Unavailable'}</button></div></article>)}</div>:<EmptyState title="No menu items found" message="Add an item or change the current filters."/>}</>
}
