import { BarChart3, Bike, Building2, ClipboardCheck, ClipboardList, FileText, LayoutDashboard, LogOut, MenuSquare, Power, Settings, Store, UserRound, Users, Utensils } from 'lucide-react'
import { Link, NavLink, Outlet, useLocation } from 'react-router-dom'
import { useAuth } from '../../core/auth/AuthContext'
import { PreferenceControls } from '../preferences/PreferenceControls'
import { usePreferences } from '../../core/preferences/PreferencesContext'

const ownerLinks = [[LayoutDashboard, 'Overview', '/owner'], [Store, 'My Restaurant', '/owner/restaurant'], [MenuSquare, 'Menu Items', '/owner/menu'], [ClipboardList, 'Orders', '/owner/orders'], [BarChart3, 'Analytics', '/owner/analytics'], [UserRound, 'Profile', '/owner/profile']] as const
const riderLinks = [[LayoutDashboard, 'Overview', '/rider'], [Bike, 'Deliveries', '/rider/deliveries'], [ClipboardList, 'Earnings', '/rider/earnings'], [Power, 'Availability', '/rider/availability'], [UserRound, 'Profile', '/rider/profile']] as const
const adminLinks = [[LayoutDashboard,'Overview','/admin'],[ClipboardCheck,'Approvals','/admin/approvals'],[Users,'Users','/admin/users'],[Building2,'Restaurants','/admin/restaurants'],[ClipboardList,'Orders','/admin/orders'],[BarChart3,'Analytics','/admin/analytics'],[FileText,'Reports','/admin/reports'],[Settings,'Profile','/admin/profile']] as const

export function PortalLayout() {
  const path=useLocation().pathname;const role=path.startsWith('/admin')?'admin':path.startsWith('/owner')?'owner':'rider';const links=role==='admin'?adminLinks:role==='owner'?ownerLinks:riderLinks;const {user,signOut}=useAuth();const {t}=usePreferences()
  return <div className={`portal portal--${role}`}><aside className="portal-sidebar"><Link className="portal-brand" to="/"><span><Utensils size={21} /></span><div><strong>Foodie</strong><small>{role==='admin'?'Administration':role==='owner'?'Restaurant portal':'Rider portal'}</small></div></Link><nav>{links.map(([Icon,label,to])=><NavLink end={to===`/${role}`} key={to} to={to}><Icon size={19}/>{t(label.toLowerCase().replaceAll(' ', '_'), label)}</NavLink>)}</nav><button className="portal-logout" onClick={signOut}><LogOut size={18}/>{t('signOut','Sign out')}</button></aside><div className="portal-main"><header className="portal-topbar"><div><span className="eyebrow">{role==='admin'?'System administrator':role==='owner'?'Restaurant partner':'Delivery partner'}</span><strong>{role==='admin'?'Foodie operations':role==='owner'?'Restaurant workspace':`Ayubowan, ${user?.name??'rider'}`}</strong></div><div className="portal-actions"><PreferenceControls /><Link to={`/${role}/profile`}><span className="avatar"><UserRound size={19}/></span><span>{user?.name}</span></Link></div></header><main className="portal-content"><Outlet/></main></div></div>
}
