import { ArrowLeft, LockKeyhole, ShoppingBag, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { QuantityStepper } from '../components/ui/QuantityStepper'
import { formatLkr, menuItems } from '../services/sriLankanData'
import { useCart } from '../store/CartContext'

export function CartPage() {
  const cart = useCart(); const delivery = cart.subtotal ? 350 : 0; const service = cart.subtotal ? 150 : 0; const total = cart.subtotal + delivery + service
  if (!cart.lines.length) return <div className="page container"><div className="empty-state empty-state--large"><ShoppingBag size={48} /><h1>Your cart is waiting</h1><p>Add something delicious from a nearby restaurant.</p><Link className="button button--primary" to="/restaurants/sushi-zen">Browse the menu</Link></div></div>
  return <div className="page container"><div className="page-title"><Link to="/restaurants"><ArrowLeft size={17} /> Continue ordering</Link><h1>Your cart <span>({cart.count} items)</span></h1></div><div className="cart-layout"><section><div className="cart-lines">{cart.lines.map((line) => <article className="cart-line" key={line.id}><img loading="lazy" src={line.image} alt={line.name} /><div><h3>{line.name}</h3><p>{line.description}</p><button className="text-button" onClick={() => cart.removeItem(line.id)}><Trash2 size={14} /> Remove</button></div><QuantityStepper value={line.quantity} onChange={(value) => cart.setQuantity(line.id, value)} /><strong>{formatLkr(line.price * line.quantity)}</strong></article>)}</div><h2 className="subheading">You might also like</h2><div className="suggestions">{menuItems.filter((item) => !cart.lines.some((line) => line.id === item.id)).slice(0, 3).map((item) => <article key={item.id}><img loading="lazy" src={item.image} alt={item.name} /><h3>{item.name}</h3><span>{formatLkr(item.price)}</span><button onClick={() => cart.addItem(item)}>Add</button></article>)}</div></section><aside className="summary-card"><h2>Order summary</h2><div className="summary-row"><span>Subtotal ({cart.count} items)</span><b>{formatLkr(cart.subtotal)}</b></div><div className="summary-row"><span>Delivery fee</span><b>{formatLkr(delivery)}</b></div><div className="summary-row"><span>Service fee</span><b>{formatLkr(service)}</b></div><div className="summary-total"><span>Total</span><strong>{formatLkr(total)}</strong></div><label>Promo code<div className="promo"><input placeholder="Enter promo code" /><button>Apply</button></div></label><Link className="button button--primary button--full" to="/checkout">Proceed to checkout</Link><button className="button button--ghost button--full" onClick={cart.clearCart}>Clear cart</button><small><LockKeyhole size={13} /> Secure checkout</small></aside></div></div>
}
