import { CreditCard, LockKeyhole, MapPin, ShoppingBag } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useCart } from '../store/CartContext'

export function CheckoutPage() {
  const cart = useCart(); const navigate = useNavigate(); const [submitted, setSubmitted] = useState(false); const total = cart.subtotal * 1.085 + 5.48
  const submit = (event: FormEvent) => { event.preventDefault(); setSubmitted(true); window.setTimeout(() => { cart.clearCart(); navigate('/orders/1234567?placed=true') }, 450) }
  if (!cart.lines.length) return <div className="page container"><div className="empty-state empty-state--large"><ShoppingBag /><h1>No items to checkout</h1><p>Add items to your cart before checking out.</p><Link className="button button--primary" to="/restaurants/sushi-zen">Browse menu</Link></div></div>
  return <div className="page container"><div className="page-title"><span className="eyebrow">Almost there</span><h1>Checkout</h1><p>Please review your details and place your order.</p></div><form className="checkout-grid" onSubmit={submit}><section className="checkout-panel"><h2><MapPin /> 1. Delivery address</h2><div className="form-grid"><label>Full name<input required placeholder="Enter your full name" defaultValue="Alice Johnson" /></label><label>Phone number<input required type="tel" placeholder="Enter your phone number" defaultValue="(555) 123-4567" /></label><label className="full">Address line 1<input required defaultValue="123 Maple Avenue" /></label><label>City<input required defaultValue="Springfield" /></label><label>ZIP code<input required defaultValue="62701" /></label><label className="full">Delivery instructions (optional)<textarea placeholder="Gate code, building details…" /></label></div><label className="check"><input type="checkbox" /> Save as default address</label><fieldset className="inline-options"><legend>Contact preference</legend><label><input type="radio" name="contact" defaultChecked /> Call</label><label><input type="radio" name="contact" /> Text</label></fieldset></section><section className="checkout-panel"><h2><CreditCard /> 2. Payment method</h2><label className="payment-choice"><input type="radio" defaultChecked /> Credit / debit card</label><div className="form-grid"><label className="full">Card number<input required inputMode="numeric" defaultValue="4242 4242 4242 4242" /></label><label>Expiry date<input required placeholder="MM / YY" defaultValue="08 / 28" /></label><label>CVV<input required placeholder="123" defaultValue="123" /></label><label className="full">Name on card<input required defaultValue="Alice Johnson" /></label></div><div className="secure-note"><LockKeyhole size={16} /> Payment information is encrypted and secure.</div></section><aside className="summary-card checkout-summary"><h2>3. Order summary</h2>{cart.lines.map((line) => <div className="mini-line" key={line.id}><img src={line.image} alt="" /><span>{line.name}<small>Qty: {line.quantity}</small></span><b>${(line.price * line.quantity).toFixed(2)}</b></div>)}<div className="summary-row"><span>Subtotal</span><b>${cart.subtotal.toFixed(2)}</b></div><div className="summary-row"><span>Fees & tax</span><b>${(total - cart.subtotal).toFixed(2)}</b></div><div className="summary-total"><span>Total</span><strong>${total.toFixed(2)}</strong></div><button className="button button--primary button--full" disabled={submitted}>{submitted ? 'Placing order…' : 'Place order'}</button></aside></form></div>
}
