import { Package, RotateCcw, X } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { orderApi } from '../core/api/services'
import { useAsyncResource } from '../core/api/useAsyncResource'
import type { ApiOrder, OrderStatus } from '../core/types/api'
import { EmptyState, ErrorState, LoadingState } from '../components/ui/AsyncState'
import { formatLkr } from '../services/sriLankanData'
const groups:Array<{label:string;statuses:OrderStatus[]}>= [{label:'Active',statuses:['placed','accepted','confirmed','preparing','ready_for_pickup','rider_assigned','picked_up','out_for_delivery']},{label:'Completed',statuses:['delivered']},{label:'Cancelled',statuses:['cancelled','declined']}]
export function CustomerOrdersConnectedPage(){const resource=useAsyncResource(orderApi.mine);const[tab,setTab]=useState(0);if(resource.loading)return <div className="page container"><LoadingState label="Loading your Foodie orders…"/></div>;if(resource.error)return <div className="page container"><ErrorState message={resource.error} retry={resource.retry}/></div>;const orders=(resource.data??[]).filter((order)=>groups[tab].statuses.includes(order.status));const cancel=async(order:ApiOrder)=>{await orderApi.cancel(order._id);await resource.retry()};return <div className="page container"><div className="page-title"><span className="eyebrow">Order history</span><h1>My orders</h1><p>Track active meals, reorder favourites and review past orders.</p></div><div className="tabs">{groups.map((group,index)=><button className={tab===index?'active':''} onClick={()=>setTab(index)} key={group.label}>{group.label}</button>)}</div>{orders.length===0?<EmptyState title={`No ${groups[tab].label.toLowerCase()} orders`} message="When an order reaches this stage, it will appear here."/>:<section className="order-list">{orders.map((order)=>{const restaurant=typeof order.restaurant==='string'?null:order.restaurant;const canCancel=!['delivered','cancelled'].includes(order.status);return <article className="order-card" key={order._id}>{restaurant?.imageUrl?<img src={restaurant.imageUrl} alt={restaurant.name}/>:<span className="order-image-fallback"><Package/></span>}<div className="order-name"><strong>Order #{order._id.slice(-6).toUpperCase()}</strong><span>{restaurant?.name??'Foodie restaurant'}</span><small>{new Date(order.createdAt).toLocaleString('en-LK')}</small></div><span><Package/> {order.items.length} items</span><b>{formatLkr(order.totalAmount)}</b><span className={`api-status api-status--${order.status}`}>{order.status.replaceAll('_',' ')}</span><div className="order-actions"><Link className="button button--secondary" to={`/orders/${order._id}`}>{order.status==='delivered'?'View order':'Track order'}</Link>{order.status==='delivered'&&<button className="button button--secondary"><RotateCcw/> Reorder</button>}{canCancel&&<button className="text-button" onClick={()=>void cancel(order)}><X/> Cancel</button>}</div></article>})}</section>}</div>}
