import { Check, Clock3, Headphones, MapPin, Package, Store, Truck } from 'lucide-react'
import { useCallback } from 'react'
import { Link, useParams } from 'react-router-dom'
import { orderApi } from '../core/api/services'
import { useAsyncResource } from '../core/api/useAsyncResource'
import { ErrorState, LoadingState } from '../components/ui/AsyncState'
import { formatLkr } from '../services/sriLankanData'
const steps=['confirmed','preparing','out_for_delivery','delivered'] as const
export function CustomerOrderDetailConnectedPage(){const{orderId=''}=useParams();const loader=useCallback(()=>orderApi.get(orderId),[orderId]);const resource=useAsyncResource(loader);if(resource.loading)return <div className="page container"><LoadingState label="Loading order details…"/></div>;if(resource.error||!resource.data)return <div className="page container"><ErrorState message={resource.error||'Order not found'} retry={resource.retry}/></div>;const order=resource.data;const restaurant=typeof order.restaurant==='string'?null:order.restaurant;const current=Math.max(0,steps.indexOf(order.status as typeof steps[number]));return <div className="page container"><div className="page-title"><Link to="/orders">‹ Back to orders</Link><h1>Order #{order._id.slice(-6).toUpperCase()}</h1><p>{new Date(order.createdAt).toLocaleString('en-LK')}</p></div><section className="tracking-card"><div className="timeline">{steps.map((step,index)=>{const Icon=[Check,Store,Truck,Package][index];return <div className={`timeline-step ${index<=current?'complete':''}`} key={step}><span><Icon/></span><strong>{step.replaceAll('_',' ')}</strong><small>{index<=current?'Updated':'Pending'}</small></div>})}</div><div className="detail-panels"><div><h3>Order details</h3><p><Store/> Restaurant <strong>{restaurant?.name??'Restaurant'}</strong></p><p><Package/> Items <strong>{order.items.length} items</strong></p><p><Clock3/> Total <strong>{formatLkr(order.totalAmount)}</strong></p></div><div><h3>Delivery details</h3><p><MapPin/> Address <strong>{order.deliveryAddress}</strong></p><p><Truck/> Status <strong>{order.status.replaceAll('_',' ')}</strong></p><p><Package/> Payment <strong>{order.paymentStatus}</strong></p></div></div><div className="order-item-summary">{order.items.map((item)=><div key={item.menuItem}><span>{item.quantity}× {item.name}</span><strong>{formatLkr(item.price*item.quantity)}</strong></div>)}</div><div className="support-banner"><Headphones/><span><strong>Need help with this order?</strong><small>Contact the Foodie help centre.</small></span><button className="button button--secondary">Get help</button></div></section></div>}
