import { Bike, CheckCircle2, Clock3, DollarSign, MapPin, Navigation, Power, Star } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { deliveryJobs } from '../../services/portalService'

export function RiderDashboard() {
  const [online,setOnline]=useState(true); const available=deliveryJobs.filter((job)=>job.status==='Available')
  return <><div className="portal-title rider-title"><div><span className="eyebrow">Ready to ride?</span><h1>Good morning, John</h1><p>Go online to receive delivery requests near you.</p></div><button className={`availability-switch ${online?'online':''}`} onClick={()=>setOnline(!online)}><Power /> <span><strong>{online?'You’re online':'You’re offline'}</strong><small>{online?'Receiving requests':'Not receiving requests'}</small></span></button></div><div className="metric-grid rider-metrics"><article><span><DollarSign /></span><div><small>Today’s earnings</small><strong>$54.80</strong><em>7 completed trips</em></div></article><article><span><Bike /></span><div><small>Weekly trips</small><strong>38</strong><em>124.6 km travelled</em></div></article><article><span><Clock3 /></span><div><small>Online time</small><strong>5h 24m</strong><em>Today</em></div></article><article><span><Star /></span><div><small>Your rating</small><strong>4.9</strong><em>Based on 182 deliveries</em></div></article></div>{online&&<section className="portal-card"><div className="portal-card__heading"><div><h2>Delivery requests near you</h2><p>{available.length} jobs are currently available</p></div><Link to="/rider/jobs">View all requests</Link></div><div className="job-preview-grid">{available.map((job)=><article key={job.id}><div className="job-payout"><span>Estimated payout</span><strong>${job.payout.toFixed(2)}</strong></div><div className="route-mini"><div><StorePin/><span><small>Pickup</small><strong>{job.restaurant}</strong><em>{job.pickup}</em></span></div><i/><div><MapPin/><span><small>Drop-off</small><strong>{job.distance} away</strong><em>{job.dropoff}</em></span></div></div><Link className="button button--primary button--full" to={`/rider/jobs/${job.id}`}>View request <Navigation /></Link></article>)}</div></section>}<section className="portal-card rider-progress"><CheckCircle2/><div><h2>Great work this week!</h2><p>You’re 2 trips away from your 40-trip weekly goal.</p></div><div><span style={{width:'95%'}}/><small>38 / 40 trips</small></div></section></>
}
function StorePin(){return <span className="route-dot"><Bike size={16}/></span>}
