import { Bike, CheckCircle2, Pencil, Star, UserRound } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { riderProfile } from '../../services/riderPortalMockData'

export function RiderProfilePage() {
  const [editing, setEditing] = useState(false)
  const [available, setAvailable] = useState(true)
  const submit = (event: FormEvent) => { event.preventDefault(); setEditing(false) }
  return <><div className="portal-title"><div><span className="eyebrow">Account & settings</span><h1>Rider profile</h1><p>Manage personal details, vehicle information, and availability.</p></div>{!editing && <button className="button button--primary" onClick={() => setEditing(true)}><Pencil /> Edit profile</button>}</div><div className="profile-settings"><section className="portal-card"><div className="rider-profile-head"><div className="rider-avatar"><UserRound /></div><div><h2>{riderProfile.name}</h2><p>Verified delivery rider</p><span><CheckCircle2 /> Available for deliveries</span></div></div><div className="profile-stat-row"><span><Star /><strong>{riderProfile.rating}</strong><small>Rating</small></span><span><Bike /><strong>{riderProfile.completed}</strong><small>Completed</small></span></div><form onSubmit={submit} className="form-grid"><label>Full name<input defaultValue={riderProfile.name} disabled={!editing} /></label><label>Phone number<input defaultValue={riderProfile.phone} disabled={!editing} /></label><label>Email address<input defaultValue={riderProfile.email} disabled={!editing} /></label><label>Vehicle type<select defaultValue={riderProfile.vehicleType} disabled={!editing}><option>Motorcycle</option><option>Bicycle</option><option>Car</option></select></label><label>Vehicle number<input defaultValue={riderProfile.vehicleNumber} disabled={!editing} /></label><label className="toggle-field">Availability<button type="button" className={`switch-control ${available ? 'active' : ''}`} onClick={() => editing && setAvailable(!available)}><span /></button><small>{available ? 'Available' : 'Unavailable'}</small></label>{editing && <div className="form-actions"><button type="button" className="button button--secondary" onClick={() => setEditing(false)}>Cancel</button><button className="button button--primary" type="submit">Save changes</button></div>}</form></section></div></>
}
