import { BrowserRouter, Route, Routes } from 'react-router-dom'
import { AppLayout } from './components/layout/AppLayout'
import { AccountConnectedPage as AccountPage } from './pages/AccountConnectedPage'
import { CartPage } from './pages/CartPage'
import { CheckoutConnectedPage as CheckoutPage } from './pages/CheckoutConnectedPage'
import { DiscoveryPage as HomePage } from './pages/DiscoveryPage'
import { SweetShopPage } from './pages/SweetShopPage'
import { FoodDetailsPage } from './pages/FoodDetailsPage'
import { NotFoundPage } from './pages/NotFoundPage'
import { CustomerOrderDetailConnectedPage as OrderDetailPage } from './pages/CustomerOrderDetailConnectedPage'
import { CustomerOrdersConnectedPage as OrdersPage } from './pages/CustomerOrdersConnectedPage'
import { CartProvider } from './store/CartContext'
import { PortalLayout } from './components/portal/PortalLayout'
import { AuthV2Page } from './pages/AuthV2Page'
import { GuestRoute, ProtectedRoute } from './core/auth/RouteGuards'
import { OwnerDashboard } from './pages/owner/OwnerDashboard'
import { OwnerOrdersV2Page } from './pages/owner/OwnerOrdersV2Page'
import { OwnerMenuConnectedPage as OwnerMenuPage } from './pages/owner/OwnerMenuConnectedPage'
import { OwnerAnalyticsConnectedPage as OwnerAnalyticsPage } from './pages/owner/OwnerAnalyticsConnectedPage'
import { OwnerProfileConnectedPage as OwnerProfilePage } from './pages/owner/OwnerProfileConnectedPage'
import { RiderConnectedDashboard as RiderDashboard, RiderConnectedJobs as RiderJobsPage, RiderConnectedDetail as RiderJobDetailPage, RiderConnectedEarnings as RiderEarningsPage } from './pages/rider/RiderConnectedPages'
import { RiderProfilePage } from './pages/rider/RiderProfilePage'
import { WalletPage } from './pages/WalletPage'
import { RestaurantsConnectedPage } from './pages/RestaurantsConnectedPage'
import { RestaurantMenuPage as RestaurantConnectedPage } from './pages/RestaurantMenuPage'
import './App.css'

export default function App() { return <BrowserRouter><CartProvider><Routes><Route element={<AppLayout />}><Route index element={<HomePage />} /><Route path="sweets" element={<SweetShopPage />} /><Route path="foods/:id" element={<FoodDetailsPage />} /><Route path="restaurants" element={<RestaurantsConnectedPage />} /><Route path="restaurants/:restaurantId" element={<RestaurantConnectedPage />} /><Route path="cart" element={<CartPage />} /><Route element={<ProtectedRoute roles={['customer']} />}><Route path="checkout" element={<CheckoutPage />} /><Route path="orders" element={<OrdersPage />} /><Route path="orders/:orderId" element={<OrderDetailPage />} /><Route path="wallet" element={<WalletPage />} /><Route path="account" element={<AccountPage />} /></Route><Route path="help" element={<NotFoundPage />} /></Route><Route element={<GuestRoute />}><Route path="login" element={<AuthV2Page mode="login" />} /><Route path="register" element={<AuthV2Page mode="register" />} /></Route><Route element={<ProtectedRoute roles={['restaurant_owner']} />}><Route path="owner" element={<PortalLayout />}><Route index element={<OwnerDashboard />} /><Route path="orders" element={<OwnerOrdersV2Page />} /><Route path="menu" element={<OwnerMenuPage />} /><Route path="analytics" element={<OwnerAnalyticsPage />} /><Route path="profile" element={<OwnerProfilePage />} /></Route></Route><Route element={<ProtectedRoute roles={['delivery_rider']} />}><Route path="rider" element={<PortalLayout />}><Route index element={<RiderDashboard />} /><Route path="jobs" element={<RiderJobsPage />} /><Route path="jobs/:id" element={<RiderJobDetailPage />} /><Route path="earnings" element={<RiderEarningsPage />} /><Route path="profile" element={<RiderProfilePage />} /></Route></Route><Route path="*" element={<NotFoundPage />} /></Routes></CartProvider></BrowserRouter> }
